### ISSUE TITLE
Issues with Control.jl

### ISSUE THREAD

**Issue by DavidDai135** [varnerlab/JuGRN-Generator#1]
1) Code generation that involves multiple activators on the same gene results in syntax error in the denominator in defining the control_array: "++" appear in denominator instead of "+"

2) Error in Control.jl involving aliasing the control function parameters (ie, W_gene_AP1_RNAP = control_parameter_dictionary["W_gene_AP1_RNAP"]). Not all of the interactions are aliased from control_parameter_dictionary and other interactions are aliased twice (repeated). When the missing aliases are referenced in the control_array later on, unknown parameter error will appear. All of the missing control parameter aliases are the ones that involve inhibition. 

Network used:

`// === main logic circuit ===================================================== //
gene_Trigger activates (gene_Trigger,gene_IRF1,gene_AhR,gene_CEBPa,gene_PU1,gene_EGR1,gene_PPARg)

// AhR -
gene_AhR activates (gene_IRF1,gene_AP1)
gene_AhR inhibits gene_PU1

// PPARg -
gene_PPARg activates (gene_OCT1,gene_IRF1,gene_CEBPa)
gene_PPARg inhibits (gene_AP1,gene_EGR1)

// CEBPa -
gene_CEBPa activates (gene_CEBPa,gene_GFI1,gene_PPARg)

// GFI1
gene_GFI1 inhibits (gene_EGR1,gene_CEBPa,gene_PU1)

// EGR1 -
gene_EGR1 activates gene_PPARg
gene_EGR1 inhibits gene_GFI1

// PU1 -
gene_PU1 activates (gene_EGR1,gene_AP1,gene_PU1)
gene_PU1 inhibits gene_PPARg

// AP1 -
gene_AP1 activates gene_PU1
gene_AP1 inhibits gene_PPARg

// OCT1-
gene_OCT1 activates gene_PU1
// ============================================================================ //
//
// === output circuit ========================================================= //

// CD38 -
(gene_IRF1,gene_PPARg,gene_Trigger) activates gene_CD38

// CD11b -
gene_PU1 activates gene_CD11b

// CD14 -
(gene_PPARg,gene_CEBPa,gene_EGR1) activates gene_CD14

// OCT4 -
gene_Trigger inhibits gene_OCT4
gene_AhR inhibits gene_OCT4

// P47Phox -
(gene_PU1,gene_CEBPa,gene_PPARg) activates gene_P47Phox
gene_PPARg inhibits gene_P47Phox

// E2F -
gene_E2F activates gene_E2F
gene_PPARg inhibits gene_E2F
gene_CEBPa inhibits gene_E2F
gene_GFI1 inhibits gene_E2F

// P21 -
(gene_Trigger,gene_AP1,gene_PPARg,gene_PU1,gene_IRF1,gene_CEBPa) activates gene_P21
gene_GFI1 inhibits gene_P21
// ============================================================================ //
`

**Comment by DavidDai135** [comment]
[GRN_HL60_Error.zip](https://github.com/varnerlab/JuGRN-Generator/files/516384/GRN_HL60_Error.zip)

**Comment by varnerlab** [comment]
Issues (1) and (2) have been corrected, and checked in the latest version.
